site_name: DeepCode Academy
site_url: https://deepcode-academy.vercel.app/
site_author: Umid
site_description: Mukammal hujjatlar sayti 🎯


theme:
  name: mkdocs


nav:
  # - Home: index.md
  - Python:
      - What is Python: python/what-is-python.md
      - Variables: python/variables.md
      - Data Types: python/data-types.md
      - Operatos: python/operators.md
      - Lists: python/lists.md
      - Tuples: python/tuples.md
      - Sets: python/sets.md
      - Dictionaries: python/dictionaries.md
      - Conditional Statements: python/conditional-statements.md
      - For Loop: python/for-loop.md
      - While Loop: python/while-loop.md
      - Functions: python/functions.md
      - Exception Handling: python/exception-handling.md
      - Moduls: python/moduls.md
      - File Handling: python/file-handling.md
      - Database: python/database.md
      - Third Party Packages: python/third-party-packages.md
      - OOP: python/oop.md

  - PostgreSQL:
    - Introduction: psql/introduction.md
    - PostgreSQL: psql/postgresql.md
    - Basic Commands: psql/basic-commands.md
    - Data Retrieval and Filtering: psql/data-retrieval-end-filtering.md
    - Function and Aggregation: psql/function-and-aggregation.md
    - Data Manipulation: psql/data-manipulation.md
    - Joins and Advanced Queries: psql/joins-and-advanced-queries.md
    - PostgreSQL connect in Python: psql/psql-connect-in-python.md
      
  - Django:
    - Introduction to Django: django/introduction-to-django.md

  - Django REST Framework:
    - Introduction to DRF: django/introduction.md