site_name: DeepCode Academy
site_url: https://deepcode-academy.vercel.app/
site_author: Umid
site_description: Mukammal hujjatlar sayti 🎯


theme:
  name: mkdocs


nav:
  # - Home: index.md
  - Python:
      - What is Python: python/what-is-python.md
      - Variables: python/variables.md
      - Data Types: python/data-types.md
      - Operatos: python/operators.md
      - Lists: python/lists.md
      - Tuples: python/tuples.md
      - Sets: python/sets.md
      - Dictionaries: python/dictionaries.md
      - Conditional Statements: python/conditional-statements.md
      - For Loop: python/for-loop.md
      - While Loop: python/while-loop.md
      - Functions: python/functions.md
      - Exception Handling: python/exception-handling.md
      - Moduls: python/moduls.md
      - File Handling: python/file-handling.md
      - Database: python/database.md
      - Third Party Packages: python/third-party-packages.md
      - OOP: python/oop.md

  - PostgreSQL:
    - Introduction: psql/introduction.md
    - PostgreSQL: psql/postgresql.md
    - Basic Commands: psql/basic-commands.md
    - Data Retrieval and Filtering: psql/data-retrieval-end-filtering.md
    - Function and Aggregation: psql/function-and-aggregation.md
    - Data Manipulation: psql/data-manipulation.md
    - Joins and Advanced Queries: psql/joins-and-advanced-queries.md
    - PostgreSQL connect in Python: psql/psql-connect-in-python.md
      
  - Django:
    - Introduction to Django: django/introduction-to-django.md
    - Django Project Structure: django/django-project-structure.md
    - Url Dispatcher and Views: django/url-dispatcher-and-views.md
    - Templates (Working with HTML): django/templates.md
    - Static Files and Bootstrap: django/static-files-and-bootstrap.md
    - Django ORM and Models: django/django-orm-and-models.md
    - Django Admin Panel: django/django-admin-panel.md
    - Django Forms: django/django-forms.md
    - CRUD Operations: django/crud-operations.md
    - QuerySet and Filtering: django/queryset-and-filtering.md
    - Django Authentication System: django/django-authentication-system.md
    - Middleware and Sessions: django/middleware-and-sessions.md
    - Class-Based Views (CBV): django/class-based-views.md
    - Django Messages Framework: django/django-messages-framework.md
    - File Upload and Media Files: django/file-upload-and-media-files.md
    - Project Planning: django/project-planning.md
    - Build Models and Database: django/build-models-and-database.md
    - Designing and Frontend: django/designing-and-frontend.md
    - Authentication and User Pages: django/authentication-and-user-pages.md
    - Deploy and Finalizations: django/deploy-and-finalizations.md


  - Django REST Framework:
    - Introduction to DRF: drf/introduction.md
    - Setting Up a Django Project and DRF: drf/setting-up-django-project-and-drf.md
    - Creating the First API: drf/creating-the-first-api.md
    - Implementing CRUD Operations: drf/implementing-crud-operations.md
    - Working with ModelSerializer: drf/working-with-modelserializer.md
    - Using Generic API Views: drf/using-generic-api-views.md
    - ViewSets and Routers: drf/viewsets-and-routers.md
    - Authentication (Token-Based Authentication): drf/authentication-token-based.md
    - Working with Permissions: drf/working-with-permissions.md
    - Throttling and Rate Limiting: drf/throttling-and-rate-limiting.md
    - Filtering, Searching, and Ordering: drf/filtering-searching-and-ordering.md
    - Working with Pagination: drf/working-with-pagination.md
    - JWT Authentication: drf/jwt-authentication.md
    - Signals and DRF: drf/signals-and-drf.md
    - Background Tasks and Celery: drf/background-tasks-and-celery.md
    - API Testing and Unit Testing: drf/api-testing-and-unit-testing.md
    - Caching and Performance Optimization: drf/caching-and-performance-optimization.md
    - WebSockets and Django Channels: drf/websockets-and-django-channels.md
    - Deployment and Docker: drf/deployment-and-docker.md
    - Advanced Concepts and Best Practices: drf/advanced-concepts-and-best-practices.md